language: ruby
rvm:
  - 2.5.3
services:
  - redis-server
script:
  - bundle install
  - bundle exec "rspec spec tests/ --exclude-pattern tests/**/search_spec.rb"
jobs:
  include:
    - stage: "Unreliable tests"
      script: bundle exec "rspec spec tests/**/search_spec.rb"
      name: "Search API tests"
