language: ruby
rvm:
  - 2.5.3
services:
  - redis-server
install:
  - gem update --system
  - bundle install
jobs:
  include:
    - stage: "Scraper regression tests"
      script: bundle exec "rspec spec tests/ --exclude-pattern tests/**/search_spec.rb"
      name: "API (non-search) tests"
    - stage: "Unreliable tests"
      script: bundle exec "rspec spec tests/**/search_spec.rb"
      name: "Search API tests"
